// <auto-generated />
using System;
using GPIMSWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GPIMSWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250604134249_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GPIMSWeb.Models.Alarm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClearedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClearedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCleared")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("Alarms");
                });

            modelBuilder.Entity("GPIMSWeb.Models.AuxData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("AuxData");
                });

            modelBuilder.Entity("GPIMSWeb.Models.CanLinData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CurrentValue")
                        .HasColumnType("float");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("MaxValue")
                        .HasColumnType("float");

                    b.Property<double>("MinValue")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("CanLinData");
                });

            modelBuilder.Entity("GPIMSWeb.Models.ChamberChillerData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ChamberChillerData");
                });

            modelBuilder.Entity("GPIMSWeb.Models.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Capacity")
                        .HasColumnType("float");

                    b.Property<int>("ChannelNumber")
                        .HasColumnType("int");

                    b.Property<double>("Current")
                        .HasColumnType("float");

                    b.Property<double>("Energy")
                        .HasColumnType("float");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<double>("Power")
                        .HasColumnType("float");

                    b.Property<string>("ScheduleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("Voltage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId", "ChannelNumber")
                        .IsUnique();

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 55.0,
                            ChannelNumber = 1,
                            Current = 1.7,
                            Energy = 28.5,
                            EquipmentId = 1,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1332),
                            Mode = 2,
                            Power = 6.46,
                            ScheduleName = "Schedule_1",
                            Status = 1,
                            Voltage = 3.8000000000000003
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 60.0,
                            ChannelNumber = 2,
                            Current = 1.8999999999999999,
                            Energy = 31.5,
                            EquipmentId = 1,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1336),
                            Mode = 1,
                            Power = 7.4100000000000001,
                            ScheduleName = "Schedule_2",
                            Status = 1,
                            Voltage = 3.9000000000000004
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 65.0,
                            ChannelNumber = 3,
                            Current = 2.1000000000000001,
                            Energy = 34.5,
                            EquipmentId = 1,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1338),
                            Mode = 2,
                            Power = 8.4000000000000004,
                            ScheduleName = "Schedule_3",
                            Status = 1,
                            Voltage = 4.0
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 70.0,
                            ChannelNumber = 4,
                            Current = 2.2999999999999998,
                            Energy = 37.5,
                            EquipmentId = 1,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1340),
                            Mode = 1,
                            Power = 9.4299999999999997,
                            ScheduleName = "Schedule_4",
                            Status = 1,
                            Voltage = 4.1000000000000005
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 75.0,
                            ChannelNumber = 5,
                            Current = 0.0,
                            Energy = 0.0,
                            EquipmentId = 1,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1342),
                            Mode = 2,
                            Power = 0.0,
                            ScheduleName = "",
                            Status = 0,
                            Voltage = 4.2000000000000002
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 80.0,
                            ChannelNumber = 6,
                            Current = 0.0,
                            Energy = 0.0,
                            EquipmentId = 1,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1360),
                            Mode = 1,
                            Power = 0.0,
                            ScheduleName = "",
                            Status = 0,
                            Voltage = 4.3000000000000007
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 85.0,
                            ChannelNumber = 7,
                            Current = 0.0,
                            Energy = 0.0,
                            EquipmentId = 1,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1361),
                            Mode = 2,
                            Power = 0.0,
                            ScheduleName = "",
                            Status = 0,
                            Voltage = 4.4000000000000004
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 90.0,
                            ChannelNumber = 8,
                            Current = 0.0,
                            Energy = 0.0,
                            EquipmentId = 1,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1390),
                            Mode = 1,
                            Power = 0.0,
                            ScheduleName = "",
                            Status = 0,
                            Voltage = 4.5
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 55.0,
                            ChannelNumber = 1,
                            Current = 1.7,
                            Energy = 28.5,
                            EquipmentId = 2,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1392),
                            Mode = 2,
                            Power = 6.46,
                            ScheduleName = "Schedule_1",
                            Status = 1,
                            Voltage = 3.8000000000000003
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 60.0,
                            ChannelNumber = 2,
                            Current = 1.8999999999999999,
                            Energy = 31.5,
                            EquipmentId = 2,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1400),
                            Mode = 1,
                            Power = 7.4100000000000001,
                            ScheduleName = "Schedule_2",
                            Status = 1,
                            Voltage = 3.9000000000000004
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 65.0,
                            ChannelNumber = 3,
                            Current = 2.1000000000000001,
                            Energy = 34.5,
                            EquipmentId = 2,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1402),
                            Mode = 2,
                            Power = 8.4000000000000004,
                            ScheduleName = "Schedule_3",
                            Status = 1,
                            Voltage = 4.0
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 70.0,
                            ChannelNumber = 4,
                            Current = 2.2999999999999998,
                            Energy = 37.5,
                            EquipmentId = 2,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1404),
                            Mode = 1,
                            Power = 9.4299999999999997,
                            ScheduleName = "Schedule_4",
                            Status = 1,
                            Voltage = 4.1000000000000005
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 75.0,
                            ChannelNumber = 5,
                            Current = 0.0,
                            Energy = 0.0,
                            EquipmentId = 2,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1405),
                            Mode = 2,
                            Power = 0.0,
                            ScheduleName = "",
                            Status = 0,
                            Voltage = 4.2000000000000002
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 80.0,
                            ChannelNumber = 6,
                            Current = 0.0,
                            Energy = 0.0,
                            EquipmentId = 2,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1406),
                            Mode = 1,
                            Power = 0.0,
                            ScheduleName = "",
                            Status = 0,
                            Voltage = 4.3000000000000007
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 85.0,
                            ChannelNumber = 7,
                            Current = 0.0,
                            Energy = 0.0,
                            EquipmentId = 2,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1407),
                            Mode = 2,
                            Power = 0.0,
                            ScheduleName = "",
                            Status = 0,
                            Voltage = 4.4000000000000004
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 90.0,
                            ChannelNumber = 8,
                            Current = 0.0,
                            Energy = 0.0,
                            EquipmentId = 2,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1408),
                            Mode = 1,
                            Power = 0.0,
                            ScheduleName = "",
                            Status = 0,
                            Voltage = 4.5
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 55.0,
                            ChannelNumber = 1,
                            Current = 1.7,
                            Energy = 28.5,
                            EquipmentId = 3,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1410),
                            Mode = 2,
                            Power = 6.46,
                            ScheduleName = "Schedule_1",
                            Status = 1,
                            Voltage = 3.8000000000000003
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 60.0,
                            ChannelNumber = 2,
                            Current = 1.8999999999999999,
                            Energy = 31.5,
                            EquipmentId = 3,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1413),
                            Mode = 1,
                            Power = 7.4100000000000001,
                            ScheduleName = "Schedule_2",
                            Status = 1,
                            Voltage = 3.9000000000000004
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 65.0,
                            ChannelNumber = 3,
                            Current = 2.1000000000000001,
                            Energy = 34.5,
                            EquipmentId = 3,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1414),
                            Mode = 2,
                            Power = 8.4000000000000004,
                            ScheduleName = "Schedule_3",
                            Status = 1,
                            Voltage = 4.0
                        },
                        new
                        {
                            Id = 20,
                            Capacity = 70.0,
                            ChannelNumber = 4,
                            Current = 2.2999999999999998,
                            Energy = 37.5,
                            EquipmentId = 3,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1416),
                            Mode = 1,
                            Power = 9.4299999999999997,
                            ScheduleName = "Schedule_4",
                            Status = 1,
                            Voltage = 4.1000000000000005
                        },
                        new
                        {
                            Id = 21,
                            Capacity = 75.0,
                            ChannelNumber = 5,
                            Current = 0.0,
                            Energy = 0.0,
                            EquipmentId = 3,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1417),
                            Mode = 2,
                            Power = 0.0,
                            ScheduleName = "",
                            Status = 0,
                            Voltage = 4.2000000000000002
                        },
                        new
                        {
                            Id = 22,
                            Capacity = 80.0,
                            ChannelNumber = 6,
                            Current = 0.0,
                            Energy = 0.0,
                            EquipmentId = 3,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1418),
                            Mode = 1,
                            Power = 0.0,
                            ScheduleName = "",
                            Status = 0,
                            Voltage = 4.3000000000000007
                        },
                        new
                        {
                            Id = 23,
                            Capacity = 85.0,
                            ChannelNumber = 7,
                            Current = 0.0,
                            Energy = 0.0,
                            EquipmentId = 3,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1419),
                            Mode = 2,
                            Power = 0.0,
                            ScheduleName = "",
                            Status = 0,
                            Voltage = 4.4000000000000004
                        },
                        new
                        {
                            Id = 24,
                            Capacity = 90.0,
                            ChannelNumber = 8,
                            Current = 0.0,
                            Energy = 0.0,
                            EquipmentId = 3,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1420),
                            Mode = 1,
                            Power = 0.0,
                            ScheduleName = "",
                            Status = 0,
                            Voltage = 4.5
                        },
                        new
                        {
                            Id = 25,
                            Capacity = 55.0,
                            ChannelNumber = 1,
                            Current = 1.7,
                            Energy = 28.5,
                            EquipmentId = 4,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1430),
                            Mode = 2,
                            Power = 6.46,
                            ScheduleName = "Schedule_1",
                            Status = 1,
                            Voltage = 3.8000000000000003
                        },
                        new
                        {
                            Id = 26,
                            Capacity = 60.0,
                            ChannelNumber = 2,
                            Current = 1.8999999999999999,
                            Energy = 31.5,
                            EquipmentId = 4,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1441),
                            Mode = 1,
                            Power = 7.4100000000000001,
                            ScheduleName = "Schedule_2",
                            Status = 1,
                            Voltage = 3.9000000000000004
                        },
                        new
                        {
                            Id = 27,
                            Capacity = 65.0,
                            ChannelNumber = 3,
                            Current = 2.1000000000000001,
                            Energy = 34.5,
                            EquipmentId = 4,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1444),
                            Mode = 2,
                            Power = 8.4000000000000004,
                            ScheduleName = "Schedule_3",
                            Status = 1,
                            Voltage = 4.0
                        },
                        new
                        {
                            Id = 28,
                            Capacity = 70.0,
                            ChannelNumber = 4,
                            Current = 2.2999999999999998,
                            Energy = 37.5,
                            EquipmentId = 4,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1445),
                            Mode = 1,
                            Power = 9.4299999999999997,
                            ScheduleName = "Schedule_4",
                            Status = 1,
                            Voltage = 4.1000000000000005
                        },
                        new
                        {
                            Id = 29,
                            Capacity = 75.0,
                            ChannelNumber = 5,
                            Current = 0.0,
                            Energy = 0.0,
                            EquipmentId = 4,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1446),
                            Mode = 2,
                            Power = 0.0,
                            ScheduleName = "",
                            Status = 0,
                            Voltage = 4.2000000000000002
                        },
                        new
                        {
                            Id = 30,
                            Capacity = 80.0,
                            ChannelNumber = 6,
                            Current = 0.0,
                            Energy = 0.0,
                            EquipmentId = 4,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1447),
                            Mode = 1,
                            Power = 0.0,
                            ScheduleName = "",
                            Status = 0,
                            Voltage = 4.3000000000000007
                        },
                        new
                        {
                            Id = 31,
                            Capacity = 85.0,
                            ChannelNumber = 7,
                            Current = 0.0,
                            Energy = 0.0,
                            EquipmentId = 4,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1448),
                            Mode = 2,
                            Power = 0.0,
                            ScheduleName = "",
                            Status = 0,
                            Voltage = 4.4000000000000004
                        },
                        new
                        {
                            Id = 32,
                            Capacity = 90.0,
                            ChannelNumber = 8,
                            Current = 0.0,
                            Energy = 0.0,
                            EquipmentId = 4,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1449),
                            Mode = 1,
                            Power = 0.0,
                            ScheduleName = "",
                            Status = 0,
                            Voltage = 4.5
                        });
                });

            modelBuilder.Entity("GPIMSWeb.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsOnline = true,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1242),
                            Name = "GPIMS-001",
                            Status = 0,
                            Version = "v2.1.0"
                        },
                        new
                        {
                            Id = 2,
                            IsOnline = true,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1247),
                            Name = "GPIMS-002",
                            Status = 0,
                            Version = "v2.1.0"
                        },
                        new
                        {
                            Id = 3,
                            IsOnline = false,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 12, 49, 747, DateTimeKind.Local).AddTicks(1249),
                            Name = "GPIMS-003",
                            Status = 2,
                            Version = "v2.0.5"
                        },
                        new
                        {
                            Id = 4,
                            IsOnline = true,
                            LastUpdateTime = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1278),
                            Name = "GPIMS-004",
                            Status = 1,
                            Version = "v2.1.0"
                        });
                });

            modelBuilder.Entity("GPIMSWeb.Models.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Number of equipment",
                            Key = "EquipmentCount",
                            UpdatedAt = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1179),
                            UpdatedBy = "System",
                            Value = "4"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Channels per equipment",
                            Key = "ChannelsPerEquipment",
                            UpdatedAt = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1181),
                            UpdatedBy = "System",
                            Value = "8"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Default system language",
                            Key = "DefaultLanguage",
                            UpdatedAt = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1182),
                            UpdatedBy = "System",
                            Value = "en"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Date format",
                            Key = "DateFormat",
                            UpdatedAt = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(1184),
                            UpdatedBy = "System",
                            Value = "yyyy-MM-dd HH:mm:ss"
                        });
                });

            modelBuilder.Entity("GPIMSWeb.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 4, 22, 42, 49, 747, DateTimeKind.Local).AddTicks(561),
                            Department = "IT",
                            IsActive = true,
                            Level = 3,
                            Name = "System Administrator",
                            PasswordHash = "$2a$11$khohGPLmyoeWR19lbKQw3.9z6XNzsaVUR1J14ck/.4foKCq0NgixW",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("GPIMSWeb.Models.UserHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserHistories");
                });

            modelBuilder.Entity("GPIMSWeb.Models.Alarm", b =>
                {
                    b.HasOne("GPIMSWeb.Models.Equipment", null)
                        .WithMany("Alarms")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GPIMSWeb.Models.AuxData", b =>
                {
                    b.HasOne("GPIMSWeb.Models.Equipment", null)
                        .WithMany("AuxData")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GPIMSWeb.Models.CanLinData", b =>
                {
                    b.HasOne("GPIMSWeb.Models.Equipment", null)
                        .WithMany("CanLinData")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GPIMSWeb.Models.Channel", b =>
                {
                    b.HasOne("GPIMSWeb.Models.Equipment", null)
                        .WithMany("Channels")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GPIMSWeb.Models.UserHistory", b =>
                {
                    b.HasOne("GPIMSWeb.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GPIMSWeb.Models.Equipment", b =>
                {
                    b.Navigation("Alarms");

                    b.Navigation("AuxData");

                    b.Navigation("CanLinData");

                    b.Navigation("Channels");
                });
#pragma warning restore 612, 618
        }
    }
}
